# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0d42e98ca98b6ac4dd5110e7d05e4c64c7923ede5912b849b1d5604b1e41b4d6f35e04175051c448cbb3b496beed4a10e4ccb4917abfa4794e8295a58de9922

test:
  secret_key_base: 28b23c33f4250b5c7cb2dbfab67eba603e0c8be11018e1b0765920742a20622a6e2a2b819bdf4d983cc27c5c990ae3e2f34be719fec7c8ce19dec91d790fe9ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
